version: "3"
services:
  mongodb:
    image: mongo:3.6
    container_name: "warehouse-db"
    hostname: service-warehouse-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: warehouse
    ports:
      - 27017:27017
    networks:
      - warehouse-network
    command: ["--bind_ip", "0.0.0.0"]

  service-warehouse:
    container_name: "service-digital-warehouse"
    build:
      context: .
      dockerfile: Dockerfile
    image: service-digital-warehouse:latest
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    networks:
      - warehouse-network
networks:
  warehouse-network:
    driver: bridge